[action] [PR:25169] [ARP_update]: Increase ARP update frequency and add retry for ping and arping (#1978)
<!--
 Please make sure you've read and understood our contributing guidelines:
 https://github.com/Azure/SONiC/blob/gh-pages/CONTRIBUTING.md

 failure_prs.log skip_prs.log Make sure all your commits include a signature generated with `git commit -s` **

 If this is a bug fix, make sure your description includes "fixes #xxxx", or
 "closes #xxxx" or "resolves #xxxx"

 Please provide the following information:
-->

#### Why I did it
This PR increases the ARP update frequency by reducing the main loop sleep interval from 300 to 120 seconds, and adds retry logic with 1 attempt (if we do need retry functionality in the future it will be easy to just change this value) and 3-second intervals between retries for ping and arping operations to improve reliability in handling transient network issues.
- For ping – check the result code with ping response (0 for succussed, non-0 for failed) and without ping response, log the result if failed and it will be helpful for debugging other traffic issues.
- For arping - check the result code with arping response and without arping response (0 for succussed, non-0 for failed), log the result if failed (Use arping for ipv4 and use ndisc6 for ipv6).
- Reworked VLAN GARP (arping) to execute per neighbor with retries.

##### Work item tracking
- Microsoft ADO **(number only)**:

#### How I did it

#### How to verify it

<!--
If PR needs to be backported, then the PR must be tested against the base branch and the earliest backport release branch and provide tested image version on these two branches. For example, if the PR is requested for master, 202211 and 202012, then the requester needs to provide test results on master and 202012.
-->

#### Which release branch to backport (provide reason below if selected)

<!--
- Note we only backport fixes to a release branch, *not* features!
- Please also provide a reason for the backporting below.
- e.g.
- [x] 202006
-->

- [ ] 202305
- [ ] 202311
- [ ] 202405
- [x] 202411
- [ ] 202505
- [x] 202511

#### Tested branch (Please provide the tested image version)

<!--
- Please provide tested image version
- e.g.
- [x] 20201231.100
-->

- [ ] <!-- image version 1 -->
- [ ] <!-- image version 2 -->

#### Description for the changelog
<!--
Write a short (one line) summary that describes the changes in this
pull request for inclusion in the changelog:
-->

<!--
 Ensure to add label/tag for the feature raised. example - PR#2174 under sonic-utilities repo. where, Generic Config and Update feature has been labelled as GCU.
-->

#### Link to config_db schema for YANG module changes
<!--
Provide a link to config_db schema for the table for which YANG model
is defined
Link should point to correct section on https://github.com/Azure/sonic-buildimage/blob/master/src/sonic-yang-models/doc/Configuration.md
-->

#### A picture of a cute animal (not mandatory but encouraged)

diff --git a/files/scripts/arp_update b/files/scripts/arp_update
--- a/files/scripts/arp_update
+++ b/files/scripts/arp_update
@@ -14,6 +14,44 @@ logger () {
     command logger -i "$$" -t "arp_update" "$@"
 }
 
+# Function to run a command with retries on failure
+run_with_retry_cmd() {
+    local desc="$1"; shift
+    local max_tries=1
+    local interval=3
+    local i=1
+
+    while [ $i -le $max_tries ]; do
+        "$@"
+        local rc=$?
+        if [ $rc -eq 0 ]; then
+            return 0
+        fi
+        if [ $i -lt $max_tries ]; then
+            logger -p warning "command '${desc}' failed on attempt ${i} (rc=${rc}); retrying (next attempt $((i + 1)) of ${max_tries})"
+            sleep $interval
+        fi
+        i=$((i + 1))
+    done
+
+    logger -p warning "command failed after ${max_tries} retries: ${desc}"
+    return 1
+}
+
+run_arping_with_retry() {
+    local ifname="$1"
+    local ip="$2"
+    run_with_retry_cmd "arping on ${ifname} to ${ip}" \
+        arping -q -w 1 -c 1 -i "$ifname" "$ip" >/dev/null 2>&1
+}
+
+run_ndisc6_with_retry() {
+    local ifname="$1"
+    local ip="$2"
+    run_with_retry_cmd "ndisc6 on ${ifname} to ${ip}" \
+        ndisc6 -q -w 1 -1 "$ip" "$ifname" >/dev/null 2>&1
+}
+
 while /bin/true; do
   # find L3 interfaces which are UP, send ipv6 multicast pings
   ARP_UPDATE_VARS=$(sonic-cfggen -d -t ${ARP_UPDATE_VARS_FILE})
@@ -53,12 +91,11 @@ while /bin/true; do
                   fi
                   intf_up=$(ip link show $interface | grep "state UP")
                   if [[ -n "$intf_up" ]]; then
-                      pingcmd="timeout 0.2 $ping_prefix -I ${interface} -n -q -i 0 -c 1 -W 1 $nexthop >/dev/null"
-                      eval $pingcmd
-                      # STALE entries may appear more often, not logging to prevent periodic syslogs
                       if [[ -z $(echo ${neigh_state} | grep 'STALE') ]]; then
                           logger "static route nexthop not resolved ($neigh_state), pinging $nexthop on $interface"
                       fi
+                      run_with_retry_cmd "static route ping to $nexthop on $interface" \
+                          timeout 0.2 $ping_prefix -I "$interface" -n -q -i 0 -c 1 -W 1 "$nexthop" >/dev/null 2>&1
                   fi
               fi
           done
@@ -91,7 +128,8 @@ while /bin/true; do
         ip="$( cut -d ',' -f 1 <<< "$neigh" )"
         mac="$( cut -d ',' -f 2 <<< "$neigh" )"
         if [[ -z $(sonic-db-cli ASIC_DB keys "ASIC_STATE:SAI_OBJECT_TYPE_FDB_ENTRY*${mac}*") ]]; then
-            timeout 0.2 ping -c1 -w1 $ip > /dev/null
+            run_with_retry_cmd "stale neighbor ping to $ip" \
+                timeout 0.2 ping -c1 -w1 "$ip" >/dev/null 2>&1
         fi
   done
 
@@ -105,7 +143,8 @@ while /bin/true; do
         if [[ $kernel_mac != $appl_db_mac ]]; then
             logger -p warning "MAC mismatch for ${ip} on ${intf} - kernel: ${kernel_mac}, APPL_DB: ${appl_db_mac}"
             ip neigh flush $ip
-            timeout 0.2 ping -c1 -w1 $ip > /dev/null
+            run_with_retry_cmd "mac mismatch ping to $ip" \
+                timeout 0.2 ping -c1 -w1 "$ip" >/dev/null 2>&1
         fi
   done
 
@@ -113,25 +152,26 @@ while /bin/true; do
   SUBTYPE=$(sonic-db-cli CONFIG_DB hget 'DEVICE_METADATA|localhost' 'subtype' | tr '[:upper:]' '[:lower:]')
   for vlan in $VLAN; do
       # generate a list of arping commands:
-      #   arping -q -w 0 -c 1 -i <VLAN interface> <IP 1>;
-      #   arping -q -w 0 -c 1 -i <VLAN interface> <IP 2>;
+      #   arping -q -w 1 -c 1 -i <VLAN interface> <IP 1>;
+      #   arping -q -w 1 -c 1 -i <VLAN interface> <IP 2>;
       #   ...
-      arpingcmd="sed -e 's/ / -i /' -e 's/^/arping -q -w 0 -c 1 /' -e 's/$/;/'"
-      ipcmd="ip -4 neigh show | grep $vlan | cut -d ' ' -f 1,3 | $arpingcmd"
-
-      eval `eval $ipcmd`
+      while read -r ip ifname; do
+          [ -z "$ip" ] && continue
+          run_arping_with_retry "$ifname" "$ip"
+      done < <(ip -4 neigh show | grep "$vlan" | awk '{print $1, $3}')
 
       # send ipv6 multicast pings to Vlan interfaces to get/refresh link-local addrs
       ping6cmd="timeout 1 ping6 -I $vlan -n -q -i 0 -c 1 -W 0 ff02::1 >/dev/null"
       eval $ping6cmd
 
       # generate a list of ndisc6 commands (exclude link-local addrs since it is done above):
-      #   ndisc6 -q -w 0 -1 <IP 1> <VLAN interface>;
-      #   ndisc6 -q -w 0 -1 <IP 2> <VLAN interface>;
+      #   ndisc6 -q -w 1 -1 <IP 1> <VLAN interface>;
+      #   ndisc6 -q -w 1 -1 <IP 2> <VLAN interface>;
       #   ...
-      ndisc6cmd="sed -e 's/^/ndisc6 -q -w 0 -1 /' -e 's/$/;/'"
-      ip6cmd="ip -6 neigh show | grep -v fe80 | grep $vlan | cut -d ' ' -f 1,3 | $ndisc6cmd"
-      eval `eval $ip6cmd`
+      while read -r ip ifname; do
+          [ -z "$ip" ] && continue
+          run_ndisc6_with_retry "$ifname" "$ip"
+      done < <(ip -6 neigh show | grep -v fe80 | grep "$vlan" | awk '{print $1, $3}')
 
       if [[ $SUBTYPE == "dualtor" ]]; then
         # capture all current failed/incomplete IPv6 neighbors in the kernel to avoid situations where new neighbors are learned
@@ -156,9 +196,10 @@ while /bin/true; do
         # generates the following command for each FAILED or INCOMPLETE IPv6 neighbor
         # timeout 0.2 ping <neighbor IPv6> -n -q -i 0 -c 1 -W 1 -I <VLAN name> >/dev/null
         if [[ ! -z "$unresolved_kernel_neighbors" ]]; then
-            ping6_template="sed -e 's/^/timeout 0.2 ping /' -e 's/,/ -n -q -i 0 -c 1 -W 1 -I /' -e 's/$/ >\/dev\/null;/'"
-            failed_ip6_neigh_cmd="echo \"$unresolved_kernel_neighbors\" | cut -d ' ' -f 1,3 --output-delimiter=',' | $ping6_template"
-            eval `eval "$failed_ip6_neigh_cmd"`
+            while read -r ip ifname; do
+                run_with_retry_cmd "failed ipv6 neighbor ping to $ip on $ifname" \
+                    timeout 0.2 ping -n -q -i 0 -c 1 -W 1 -I "$ifname" "$ip" >/dev/null 2>&1
+            done < <(echo "$unresolved_kernel_neighbors" | awk '{print $1, $3}')
             # allow some time for any transient INCOMPLETE neighbors to transition to FAILED
             sleep 5
         fi
@@ -180,7 +221,7 @@ while /bin/true; do
 
 
   # sleep here before handling the mismatch as it is not required during startup
-  sleep 300
+  sleep 120
 
   # refresh neighbor entries from APP_DB in case of mismatch with kernel
   DBNEIGH=$(sonic-db-cli APPL_DB keys NEIGH_TABLE*)
@@ -204,13 +245,13 @@ while /bin/true; do
       ip="$( cut -d ':' -f 3- <<< "$neigh" )"
       if [[ $intf == *"Vlan"* ]]; then
           if [[ $ip == *"."* ]] && [[ ! $KERNEIGH4 =~ "${ip},${intf}" ]]; then
-              pingcmd="timeout 0.2 ping -I $intf -n -q -i 0 -c 1 -W 1 $ip >/dev/null"
-              eval $pingcmd
               logger "mismatch arp entry, pinging ${ip} on ${intf}"
+              run_with_retry_cmd "db/kernel mismatch ping to ${ip} on ${intf}" \
+                timeout 0.2 ping -I "$intf" -n -q -i 0 -c 1 -W 1 "$ip" >/dev/null 2>&1
           elif [[ $ip == *":"* ]] && [[ ! $KERNEIGH6 =~ "${ip},${intf}" ]]; then
-              ping6cmd="timeout 0.2 ping6 -I $intf -n -q -i 0 -c 1 -W 1 $ip >/dev/null"
-              eval $ping6cmd
               logger "mismatch v6 nbr entry, pinging ${ip} on ${intf}"
+              run_with_retry_cmd "db/kernel mismatch ping6 to ${ip} on ${intf}" \
+                timeout 0.2 ping6 -I "$intf" -n -q -i 0 -c 1 -W 1 "$ip" >/dev/null 2>&1
           fi
       fi
   done
